export const Actions = {
  GET_BANNER: "GET_BANNER",
  GET_BANNER_SUCCESS: "GET_BANNER_SUCCESS",
  GET_BANNER_FAIL: "GET_BANNER_FAIL",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_FAIL: "GET_CATEGORIES_FAIL",
};
